### ISSUE TITLE
contextmenu plugin bug with classic skin?

### ISSUE THREAD

**Issue by jsedwick** [JohnDoh/Roundcube-Plugin-Context-Menu#72]
Using this version of the contextmenu plugins (https://github.com/JohnDoh/Roundcube-Plugin-Context-Menu/releases/tag/2.1.2) with the classic skin for rc 1.1.3, the "List options..." modal window appears behind the rest of the interface when clicked. And the contextmenu links trigger it to show/hide back there, as well. Is this a known issue or am I making this up?

Note: works fine with Larry

Thank you

![screen shot 2015-10-22 at 11 52 16 am](https://cloud.githubusercontent.com/assets/1263723/10675163/8239bac6-78b3-11e5-826d-7ac9c9c0eeea.png)

**Comment by JohnDoh** [comment]
It looks like you have a few CSS problem from that screenshot.

Was this an upgrade or a fresh install of rc?
Are there any JS errors in the browser's console?
And just to be sure, because I cannot recreate it, if you disabled the contextmenu plugin then everything goes back to normal?
Finally, do you have any other plugins runnig?

**Comment by jsedwick** [comment]
Thanks for the reply!

This was an upgrade and while there are no JS errors in the console it could very well be the result of one of the several other outdated plugins causing the issue. 

I'll followup later if necessary but I'm satisfied at this point this isn't a context menu plugin bug. I appreciate you looking into it!
