### ISSUE TITLE
how to add submenu items?

### ISSUE THREAD

**Issue by mike-kfed** [JohnDoh/Roundcube-Plugin-Context-Menu#82]
I am the developer of the thunderbird-labels plugin for roundcube. I integrated support of contextmenu many years ago to my plugin. I never
used it myself, over time contextmenu support broke which I recently found out. Back then I was able to add an entry that would pop out a submenu,
similar to how "forward mail" menu looks now. I was not able to recreate that in
the current version (roundcube 1.3beta, contextmenu git-master). I managed
to add many main-menu items to the contextmenu, but since IMAP labels are
many, that is not very user friendly.

Reading your javascript code, you seem to expect
`onclick="UI.toggle_popup('someid', event)"` in the button of the parent menu item, to
create a submenu. My plugins code does not have that, they have
normal `onclick="return rcmail.command(...)"` calls created by roundcubes html output
api. How can I add a submenu to your contextmenu? Do I have to kinda fake a default roundcube toolbar menu or is there another way?

My current attempt can be seen in my branch called "arbitrary_labels"

https://github.com/mike-kfed/rcmail-thunderbird-labels/tree/arbitrary_labels

thanks in advance for any advice

**Comment by JohnDoh** [comment]
please see my PR. its mostly. Because the menu item does not match the format used in the Roundcube core then the contextmenu plugin has some issues detecting it and knowing what to do with it. In tb_label_contextmenu.js I've put in some code to overwrite the default functionality and add the item to the menu.

I also had to make a change in, tb_label.js. I've put the onclick function for the labels into its own function so that the contextmenu plugin can call it directly - after it has setup the message selection.

**Comment by mike-kfed** [comment]
oh, wow, thanks a lot! I will reverse engineer that to fit into my coffescripts! (tb_label.js and tb_label_contextmenu.js are generated from there actually)
