### ISSUE TITLE
Compatibility with kolab_tags plugin

### ISSUE THREAD

**Issue by alecpl** [JohnDoh/Roundcube-Plugin-Context-Menu#87]
https://git.kolab.org/diffusion/RPK/browse/master/plugins/kolab_tags/

The plugin extends "Mark" menu with three additional items. Two of them display sub-menu. This submenu does not work in following scenario:

1. Open mail UI with messages list
2. Make sure no messages are selected
3. Right-click any message
4. Click Mark > Tag as... in the contextmenu. See no sub-menu is being open.

Note the plugin requires libkolab plugin that can be found in the same repo. It might not fully work as it requires Kolab, but for testing just this UI issue it's enough to just install these two plugins.

Any help?

**Comment by JohnDoh** [comment]
It looks like there are a few different issues here:

1. Tags dialog hidden on message list selection change
The dialog is hidden is hidden any time the selection in the message list changes [kolab_tags.js#L596](https://git.kolab.org/diffusion/RPK/browse/master/plugins/kolab_tags/kolab_tags.js;c5843388a8bb92d648b347345c20c70327c30cce$596). The contextmenu plugin works by changing the message list selection to match the current target, executing what ever roundcube command was clicked and then putting the original selection back. So when you click on "Tag as..." a command is run, the message list selection is changed by the contextmenu plugin to match the targeted messages and this change is tiggering the hide event in kolab_tags.

Changing the message list selection is kinda fundermental to the functionality of the contextmenu as most of roundcube's core actions rely on message list selection. So the only way around this might be to change how the tags dialog is hidden, perhops use the body click event similiar to what is done for popup menus rather than list selection change?

2. There is a chain of actions to add a tag
Similar to the move/copy functions adding a tag is a chain of actions, the first action opens the dialog and then later another action adds the tag. The contextmenu plugin has a problem there because of the way message list selections are changed and then restored. At the time of the second action the message list selection has already been put back to its original state.  I have a function which overrides the selection when move/copy is done to get around this - see [contextmenu.js#L832](https://github.com/JohnDoh/Roundcube-Plugin-Context-Menu/blob/master/contextmenu.js#L832) and other plugins can extend that by doing something like:
```js
if (rcmail.context_menu_settings)
  rcmail.context_menu_settings.overload_commands.push('tag-add');
```
But....

3. Roundcube does not allow one plugin to interact with a JS command from another plugin
In app.js around [line 729](https://github.com/roundcube/roundcubemail/blob/master/program/js/app.js#L729) external commands are executed before the ```actionbefore``` event is triggered and ```actionbefore``` and ```actionafter``` is how the contextmenu can change the message list selection for these chained actions.

Having to registed these "overloaded" commands like move and copy is not the nicest thing and certainly not great for compatibility with other plugins but even if there was another way - may be detect that a popup was opened, then assume the selection must be changed for the next command? - right now it would not help since the core will execute the external command before giving contextmenu a chance to do anything with the selection.

**Comment by JohnDoh** [comment]
This change d18f352 (very rough, work in progress) relies on a new hook being added in the rc core in list.js
```diff
--- a/program/js/list.js
+++ b/program/js/list.js
@@ -1257,7 +1257,12 @@ clear_selection: function(id, no_event)
  */
 get_selection: function(deep)
 {
-  var res = $.merge([], this.selection);
+  var res = null;
+
+  if (res = this.triggerEvent('getselection', deep))
+    return res;
+
+  res = $.merge([], this.selection);

   // return children of selected threads even if only root is selected
   if (deep !== false && res.length) {
```
this would allow plugins, like the contextmenu to provide different selection information when needed. this removes the needs for the contextmenu to change the selection all the time and takes care of issue 1 and 3 above I think. 2 is still an issue as the command has to be enabled

**Comment by alecpl** [comment]
I added getselection event in https://github.com/roundcube/roundcubemail/commit/e9eb87d6f4e39483fd21a998bd3ac2c13680c98e

**Comment by JohnDoh** [comment]
This might not have been so straight forward as I thought, There are places in app.js and in plugins (that come with the core) that use [list widget].selection directly so the hook is never called.

**Comment by JohnDoh** [comment]
PR also appears to fix num 2 listed above

**Comment by JohnDoh** [comment]
I think this issue might be sorted now. Please test your tags plugin again with the latest git-master

**Comment by alecpl** [comment]
Works like a harm. Thank you.
